[package]
name = "bui-backend"
description = "Brower User Interfaces (BUIs) with Tokio"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
documentation = "https://docs.rs/bui-backend/"
repository = "https://github.com/astraw/bui-backend"
readme = "README.md"
keywords = ["server", "reactive", "server sent events", "futures", "tokio"]
license = "MIT/Apache-2.0"

[dependencies]
bui-backend-codegen = {path="codegen", default-features = false}
futures = "0.1.11"
includedir = "0.2.0"
hyper = "0.11"
rand = "0.3"
raii-change-tracker = "0.1"
error-chain = "0.10.0"
log = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = {version = "1.0"}
jsonwebtoken = {version="2"}
uuid = { version = "0.5", features = ["v4", "serde"] }

[features]
default = ["bundle_files"]
bundle_files = ["bui-backend-codegen/bundle_files"]
serve_files = ["bui-backend-codegen/serve_files"]

[workspace]
members = [
    "codegen",
    "bui-demo",
]
