[package]
name = "bui-demo"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
build = "build.rs"
repository = "https://github.com/astraw/bui-backend"
license = "MIT/Apache-2.0"

[dependencies]
bui-backend = {version="0.2", default-features = false, path=".."}
log = "0.3.6"
env_logger = "0.4"
raii-change-tracker = "0.1"
includedir = "0.2.0"
phf = "0.7.12"
serde = "1.0"
serde_json = "1.0"
clap = "2.20.0"
error-chain = "0.11"
hyper = "0.11"
dotenv = "0.10"
futures = "0.1"
tokio-core = "0.1"
bui-demo-data = {path="bui-demo-data"}

[build-dependencies]
bui-backend-codegen = {version = "0.1", default-features = false, path="../codegen"}

[features]
default = ["bundle_files", "frontend_js"]

# Bundle files into executable
bundle_files = ["bui-backend/bundle_files", "bui-backend-codegen/bundle_files"]
# Serve files from disk at runtime
serve_files = ["bui-backend/serve_files", "bui-backend-codegen/serve_files"]

# Use the Javascript frontend
frontend_js = []
# Use the Elm frontend
frontend_elm = []
# Use the Rust frontend
frontend_rust_wasm = []
