[package]
name = "bui-demo-frontend-rust-wasm"
version = "0.2.1"
authors = ["Andrew Straw <strawman@astraw.com>"]

[dependencies]
stdweb = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# Bypass (for now) build errors when this is in the workspace below me.
[workspace]
members = []
