on: [push]
name: CI
jobs:
  build_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build

  build_MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build

  build_Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build

  build_demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bui-demo
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo build

  build_demo_serve_files:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bui-demo
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo build --no-default-features --features serve_files,frontend_js

  build_demo_frontend_yew:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bui-demo/frontend_yew
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
    - run: ./build.sh

  build_demo_frontend_seed:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bui-demo/frontend_seed
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
    - run: ./build.sh
